import type { Locale } from '@/i18n/config'

/** Demo labels inside the illustrations. Numbers stay identical across languages. */
export const labels = {
  de: {
    occupancy: 'Auslastung',
    adr: 'ADR',
    revpar: 'RevPAR',
    bookings: 'Buchungen',
    direct: 'Direkt',
    ota: 'OTA',
    plan: 'Plan',
    lastYear: 'Vorjahr',
    thisYear: 'Dieses Jahr',
    healthy: 'Gesund',
    syncing: 'Aktualisiert',
    question: 'Warum ist der Pickup diese Woche höher?',
    answer: 'Vor allem mehr Direktbuchungen fürs Wochenende: +18 % gegenüber der Vorwoche.',
    you: 'Du',
    agent: 'Resi',
    space: 'Space',
    owner: 'Owner',
    admin: 'Admin',
    reader: 'Leser',
    twoFactor: '2FA',
    pickup: 'Pickup diese Woche',
    otaShare: 'OTA-Anteil über Ziel',
    cpb: 'Kosten pro Buchung',
    week: 'Woche',
    march: 'März',
    vsLastYear: 'vs. Vorjahr',
    ask: 'Frage stellen …',
    q1: 'Wie war die Auslastung letzte Woche?',
    q2: 'Welche Kanäle bringen die meisten Direktbuchungen?',
    a1: 'Letzte Woche lag die Auslastung bei 84 %, 6 Punkte über der Vorwoche.',
    lastWeek: 'letzte Woche',
    months: ['Jan', 'Feb', 'Mär', 'Apr', 'Mai', 'Jun'],
    scenes: {
      assistant: 'Resi',
      builder: {
        title: 'Resi baut ein Dashboard aus einem Satz: Kennzahlen wählen, Daten lesen, Widgets anordnen',
        prompt: 'Dashboard für Q4: Auslastung, ADR, Kanalmix',
        intro: 'Ich baue das Dashboard:',
        steps: ['Kennzahlen aus dem Katalog gewählt', 'Kanalmix und Buchungen aus Mews', 'Plan vs. Ist aus dem Q4-Budget'],
        done: 'Dashboard gespeichert · Link kopiert',
        dashboard: 'Q4 Übersicht',
        period: 'Okt – Dez',
        other: 'Sonstige',
      },
      channelMix: 'Kanalmix',
      bookingsByWeek: 'Buchungen pro Woche',
      vsPlan: 'vs. Plan',
      schedule: 'Montag, 08:00',
      reportTitle: 'Wochenreport · KW 37',
      reportKind: 'per E-Mail',
      delivered: 'Zugestellt',
      recipients: ['Geschäftsführung', 'Eigentümer', 'Revenue-Team'],
      post: {
        title: 'Flying KPIs: Montag um 08:00 wird der Wochenreport erstellt, Resi ergänzt drei Highlights und drei Empfänger bekommen ihn zugestellt',
        schedule: 'Montag · 08:00',
        repeat: 'jede Woche',
        highlights: 'Resi · 3 Highlights',
        points: ['Direktbuchungen +18 % zur Vorwoche', 'OTA-Anteil 4 Punkte über Ziel', 'Wochenende zu 96 % belegt'],
        recipients: [
          { name: 'Geschäftsführung', via: 'Dashboard per E-Mail', kind: 'dashboard' },
          { name: 'Eigentümer', via: 'Digest per E-Mail', kind: 'digest' },
          { name: 'Revenue-Team', via: 'Dashboard per E-Mail', kind: 'dashboard' },
        ],
        scheduled: 'Geplant',
        delivered: 'Zugestellt',
      },
      group: {
        title: 'Hotelgruppe: vier Häuser mit eigenem PMS und eigenem Space laufen in der Zentrale zusammen, die sie nach Auslastung, ADR und RevPAR ordnet',
        ownSpace: 'eigener Space',
        node: 'Gruppe',
        nodeNote: '4 Spaces, 1 Login',
        board: 'Zentrale',
        above: 'über Plan',
        near: 'knapp darunter',
        below: 'unter Plan',
      },
      agency: {
        title: 'Agentur: ein Login, drei Kunden nacheinander. Kampagnen treffen Buchungen aus dem PMS, der Monatsreport geht im Branding des Kunden raus und der Kunde antwortet',
        who: 'Lena',
        role: 'Agentur · 12 Kunden',
        clients: ['Hotel Alpenrose', 'Seeblick Resort', 'Bergwald Lodge'],
        more: '9 weitere Kunden',
        join: 'Kampagne × Buchung',
        bookings: 'Buchungen aus Kampagnen',
        report: 'Monatsreport September',
        spend: 'Werbekosten',
        revenue: 'Umsatz',
        byEmail: 'per E-Mail',
        sent: 'Beim Kunden',
        replies: ['Budget für Oktober ist freigegeben.', 'Microsoft Ads bitte weiterlaufen lassen.', 'Newsletter ab KW 42, passt für uns.'],
      },
      roi: 'ROI',
      planVsActual: 'Plan vs. Ist',
      scheduled: 'Geplant',
      created: 'Erstellt',
      sent: 'Gesendet',
      resi: {
        title: 'Resi bei der Arbeit: Quellen, Kennzahl-Definition und Rechte fließen in jede Antwort',
        role: 'Deine KI-Analystin',
        thinking: 'Resi prüft die Kennzahlen …',
        catalogue: 'KPI-Katalog',
        permissions: 'Rechte wie in der App',
        scope: 'Space Alpenrose · Revenue-Team',
        source: 'Quelle',
        turns: [
          {
            q: 'Wie war die Auslastung letzte Woche?',
            a: '84 %, sechs Punkte über der Vorwoche. Der Zuwachs kam fast ganz aus Direktbuchungen.',
            kpi: 'Auslastung · KW 37',
            value: 84,
            unit: ' %',
            delta: '+6',
            up: true,
            lang: 'DE',
            def: 'Auslastung · v1.2',
          },
          {
            q: 'Hat die Sommerkampagne auf Meta den Plan erreicht?',
            a: 'Fast: 212 statt 240 Buchungen, dafür 168 € ADR über Plan. Die Lücke liegt in KW 29 bis 31.',
            kpi: 'Buchungen · Sommerkampagne',
            value: 212,
            unit: '',
            delta: '−28',
            up: false,
            lang: 'DE',
            def: 'Kampagnen-Buchungen · v2.0',
          },
          {
            q: 'Quale mercato porta l’ADR più alto?',
            a: 'Gli ospiti svizzeri: 189 € di ADR con 4,2 notti. Il 71 % prenota direttamente.',
            kpi: 'ADR · Svizzera',
            value: 189,
            unit: ' €',
            delta: '+31 %',
            up: true,
            lang: 'IT',
            def: 'ADR · v1.1',
          },
        ],
      },
      hub: {
        title: 'Resi im Zentrum: Datenquellen fließen in den Chat, jede Antwort wird zu Kennzahl oder Diagramm',
        role: 'Deine KI-Analystin',
        ask: 'Frag Resi …',
        thinking: 'Resi prüft die Kennzahlen …',
        catalogue: 'KPI-Katalog',
        turns: [
          {
            q: 'Wie war die Auslastung letzte Woche?',
            a: '84 %, sechs Punkte über der Vorwoche. Der Zuwachs kam fast ganz aus Direktbuchungen.',
            source: 'Mews · Google Analytics',
            def: 'occupancy = rooms_sold / rooms_available',
          },
          {
            q: 'Hat die Meta-Kampagne den Plan erreicht?',
            a: 'Fast: 212 von 240 Buchungen. Die Lücke liegt in KW 29 bis 31.',
            source: 'Meta Ads · Mews',
            def: 'campaign_bookings = bookings where utm = meta',
          },
          {
            q: 'Wie läuft der Pickup für Oktober?',
            a: '12 % über Vorjahr, getragen von Google Ads. Ich schicke es Montag ans Revenue-Team.',
            source: 'Mews · Google Ads',
            def: 'pickup = Δ on_the_books per day',
          },
        ],
        kpi: { label: 'Auslastung · KW 37', delta: '+6' },
        bars: { title: 'Buchungen Meta-Kampagne', value: '212 / 240', actual: 'Ist', plan: 'Plan', from: 'KW 27', to: 'KW 34' },
        line: { title: 'Pickup Oktober', delta: '+12 %', current: '2026', last: 'Vorjahr' },
      },
      semantic: {
        catalogue: 'Kennzahlen-Katalog',
        collection: 'KPI-Sammlung Revenue',
        definition: 'Definition',
        formula: 'Formel',
        dimensions: 'Dimensionen',
        version: 'Version',
        guests: 'Gästedaten: nicht enthalten',
        same: 'Dreimal dieselbe Zahl, eine Definition',
        consumers: ['Dashboard', 'Resi', 'Claude · MCP'],
        kpis: [
          { name: 'RevPAR', formula: 'net_revenue / rooms_available', dims: 'Kanal · Zimmerkategorie · Ankunft', version: 'v1.2', value: '119 €' },
          { name: 'ADR', formula: 'net_revenue / rooms_sold', dims: 'Kanal · Herkunft · Ankunft', version: 'v1.1', value: '142 €' },
          { name: 'Auslastung', formula: 'rooms_sold / rooms_available', dims: 'Zimmerkategorie · Ankunft', version: 'v1.0', value: '84 %' },
        ],
        others: ['Werbekosten', 'Anfragen'],
      },
      dimensions: {
        kpi: 'Pickup · 7 Tage',
        nights: 'Nächte',
        grouping: 'Gruppierung',
        groups: [
          { name: 'Kanal', bars: [['Direkt', 92], ['Booking', 58], ['Expedia', 34], ['Telefon', 22]] },
          { name: 'Zimmerkategorie', bars: [['Doppel', 84], ['Superior', 62], ['Suite', 30], ['Einzel', 44]] },
          { name: 'Herkunft', bars: [['DE', 88], ['CH', 52], ['AT', 40], ['IT', 26]] },
        ],
        perspective: 'Perspektive',
        perspectives: [
          { name: 'Buchungsdatum', field: 'booking.created_at', value: '38' },
          { name: 'Ankunft', field: 'reservation.arrival', value: '52' },
        ],
        linked: 'Über Sammlungen hinweg',
        link: ['Kampagne', 'Google Ads ↔ Mews', 'verknüpft'],
        inWidgets: 'In jedem Widget wählbar',
      },
      collections: {
        title: 'KPI-Sammlung',
        name: 'Hotel-Standard',
        version: 'v2.3',
        counts: '24 Kennzahlen · 9 Dimensionen',
        items: ['Auslastung', 'ADR', 'RevPAR', 'Pickup', 'Kosten je Buchung', 'Anfragen'],
        owner: 'Gepflegt von: Zentrale',
        released: 'Freigegeben',
        readOnly: 'Lesend · Updates kommen an',
        groups: [
          { name: 'Hotelgruppe', members: ['Alpenrose', 'Seeblick', 'Bergwald'] },
          { name: 'Kunden', members: ['Hotel Post', 'Villa Laguna'] },
          { name: 'Community', members: ['Öffentlich · 140 Spaces'] },
        ],
      },
      sync: {
        title: 'Sync: selbst verbinden oder einen sicheren Link an Kollegin oder Kunde schicken, die Historie wird geladen, danach nur noch Neues, Duplikate entfernt und Daten bereinigt, bereit für Dashboards, Resi und MCP',
        connect: 'Verbinden',
        noPassword: 'Du siehst kein Passwort',
        methods: [
          { who: 'Du', role: 'verbindest selbst', action: 'Mit Mews anmelden' },
          { who: 'Anna', role: 'Kollegin, Marketing', action: 'Link an Anna' },
          { who: 'Seeblick Resort', role: 'Kunde', action: 'Link an den Kunden' },
        ],
        once: 'einmalig gültig',
        expires: '7 Tage gültig',
        waiting: 'Wartet auf Freigabe',
        connected: 'Verbunden',
        approved: 'Freigegeben',
        gate: 'Dedupe & Cleanse',
        dupes: 'doppelt',
        cleaned: 'bereinigt',
        datasets: ['Reservierungen', 'Kampagnen & Kosten', 'Buchungen'],
        rows: 'Zeilen',
        history: 'Historie 13 Monate',
        then: 'danach stündlich',
        upToDate: 'Aktuell',
        readyFor: 'Bereit für',
      },
      verify: {
        title: 'Resi arbeitet im Dashboard: Sie beantwortet eine Frage mit geprüfter Quelle und legt das Diagramm selbst als Widget ab, dann baut sie das ADR-Widget auf Wunsch je Kanal um',
        dashboard: 'Q4 Übersicht',
        period: 'Okt – Dez',
        turns: [
          { context: 'Q4 Übersicht', q: 'Wie hat sich die ADR im Oktober entwickelt?', a: '−3,1 % auf 138 €, vor allem durch mehr OTA-Buchungen unter der Woche.' },
          { context: 'ADR-Widget', q: 'Zeig die ADR im Widget lieber je Kanal.', a: 'Erledigt: Das ADR-Widget zeigt jetzt Direkt, OTA und Sonstige.' },
        ],
        thinking: 'Resi prüft den KPI-Katalog …',
        chart: 'ADR Oktober, je Woche',
        source: 'ADR v1.1 aus dem KPI-Katalog',
        verified: 'geprüft',
        placing: 'Resi legt es aufs Dashboard …',
        placed: 'Als Widget auf dem Dashboard',
        slot: 'Neues Widget',
        created: 'neu von Resi',
        edited: 'von Resi bearbeitet',
        other: 'Sonstige',
      },
    },
  },
  en: {
    occupancy: 'Occupancy',
    adr: 'ADR',
    revpar: 'RevPAR',
    bookings: 'Bookings',
    direct: 'Direct',
    ota: 'OTA',
    plan: 'Plan',
    lastYear: 'Last year',
    thisYear: 'This year',
    healthy: 'Healthy',
    syncing: 'Synced',
    question: 'Why is pickup higher this week?',
    answer: 'Mostly more direct bookings for the weekend: +18 % versus last week.',
    you: 'You',
    agent: 'Resi',
    space: 'Space',
    owner: 'Owner',
    admin: 'Admin',
    reader: 'Reader',
    twoFactor: '2FA',
    pickup: 'Pickup this week',
    otaShare: 'OTA share above target',
    cpb: 'Cost per booking',
    week: 'Week',
    march: 'March',
    vsLastYear: 'vs. last year',
    ask: 'Ask a question …',
    q1: 'What was occupancy last week?',
    q2: 'Which channels bring the most direct bookings?',
    a1: 'Occupancy was 84 % last week, 6 points above the week before.',
    lastWeek: 'last week',
    months: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
    scenes: {
      assistant: 'Resi',
      builder: {
        title: 'Resi builds a dashboard from one sentence: choosing KPIs, reading data, placing widgets',
        prompt: 'Q4 dashboard: occupancy, ADR, channel mix',
        intro: 'Building the dashboard:',
        steps: ['KPIs picked from the catalogue', 'Channel mix and bookings from Mews', 'Plan vs. actual from the Q4 budget'],
        done: 'Dashboard saved · link copied',
        dashboard: 'Q4 overview',
        period: 'Oct – Dec',
        other: 'Other',
      },
      channelMix: 'Channel mix',
      bookingsByWeek: 'Bookings per week',
      vsPlan: 'vs. plan',
      schedule: 'Monday, 08:00',
      reportTitle: 'Weekly report · week 37',
      reportKind: 'by email',
      delivered: 'Delivered',
      recipients: ['Management', 'Owners', 'Revenue team'],
      post: {
        title: 'Flying KPIs: on Monday at 08:00 the weekly report is created, Resi adds three highlights and three recipients receive it',
        schedule: 'Monday · 08:00',
        repeat: 'every week',
        highlights: 'Resi · 3 highlights',
        points: ['Direct bookings +18 % on last week', 'OTA share 4 points above target', 'Weekend 96 % booked'],
        recipients: [
          { name: 'Management', via: 'Dashboard by email', kind: 'dashboard' },
          { name: 'Owners', via: 'Digest by email', kind: 'digest' },
          { name: 'Revenue team', via: 'Dashboard by email', kind: 'dashboard' },
        ],
        scheduled: 'Scheduled',
        delivered: 'Delivered',
      },
      group: {
        title: 'Hotel group: four properties, each with its own PMS and space, come together at head office, which ranks them by occupancy, ADR and RevPAR',
        ownSpace: 'own space',
        node: 'Group',
        nodeNote: '4 spaces, 1 login',
        board: 'Head office',
        above: 'above plan',
        near: 'just below',
        below: 'below plan',
      },
      agency: {
        title: 'Agency: one login, three clients in turn. Campaigns meet bookings from the PMS, the monthly report goes out in the client’s branding and the client replies',
        who: 'Lena',
        role: 'Agency · 12 clients',
        clients: ['Hotel Alpenrose', 'Seeblick Resort', 'Bergwald Lodge'],
        more: '9 more clients',
        join: 'Campaign × booking',
        bookings: 'Bookings from campaigns',
        report: 'Monthly report September',
        spend: 'Ad spend',
        revenue: 'Revenue',
        byEmail: 'by email',
        sent: 'With the client',
        replies: ['October budget is approved.', 'Please keep Microsoft Ads running.', 'Newsletter from week 42 works for us.'],
      },
      roi: 'ROI',
      planVsActual: 'Plan vs. actual',
      scheduled: 'Scheduled',
      created: 'Created',
      sent: 'Sent',
      resi: {
        title: 'Resi at work: sources, KPI definitions and permissions flow into every answer',
        role: 'Your AI analyst',
        thinking: 'Resi is checking the figures …',
        catalogue: 'KPI catalogue',
        permissions: 'Same permissions as in the app',
        scope: 'Space Alpenrose · revenue team',
        source: 'Source',
        turns: [
          {
            q: 'How was occupancy last week?',
            a: '84 %, six points above the week before. Almost all of the gain came from direct bookings.',
            kpi: 'Occupancy · week 37',
            value: 84,
            unit: ' %',
            delta: '+6',
            up: true,
            lang: 'EN',
            def: 'Occupancy · v1.2',
          },
          {
            q: 'Did the summer campaign on Meta hit plan?',
            a: 'Almost: 212 bookings against 240, but with an ADR of €168 above plan. The gap sits in weeks 29 to 31.',
            kpi: 'Bookings · summer campaign',
            value: 212,
            unit: '',
            delta: '−28',
            up: false,
            lang: 'EN',
            def: 'Campaign bookings · v2.0',
          },
          {
            q: 'Quale mercato porta l’ADR più alto?',
            a: 'Gli ospiti svizzeri: 189 € di ADR con 4,2 notti. Il 71 % prenota direttamente.',
            kpi: 'ADR · Svizzera',
            value: 189,
            unit: ' €',
            delta: '+31 %',
            up: true,
            lang: 'IT',
            def: 'ADR · v1.1',
          },
        ],
      },
      hub: {
        title: 'Resi at the centre: data sources flow into the chat, every answer becomes a KPI or a chart',
        role: 'Your AI analyst',
        ask: 'Ask Resi …',
        thinking: 'Resi is checking the figures …',
        catalogue: 'KPI catalogue',
        turns: [
          {
            q: 'How was occupancy last week?',
            a: '84 %, six points above the week before. Almost all of the gain came from direct bookings.',
            source: 'Mews · Google Analytics',
            def: 'occupancy = rooms_sold / rooms_available',
          },
          {
            q: 'Did the Meta campaign hit plan?',
            a: 'Almost: 212 of 240 bookings. The gap sits in weeks 29 to 31.',
            source: 'Meta Ads · Mews',
            def: 'campaign_bookings = bookings where utm = meta',
          },
          {
            q: 'How is October pickup looking?',
            a: '12 % above last year, carried by Google Ads. I will send it to the revenue team on Monday.',
            source: 'Mews · Google Ads',
            def: 'pickup = Δ on_the_books per day',
          },
        ],
        kpi: { label: 'Occupancy · week 37', delta: '+6' },
        bars: { title: 'Meta campaign bookings', value: '212 / 240', actual: 'Actual', plan: 'Plan', from: 'Wk 27', to: 'Wk 34' },
        line: { title: 'October pickup', delta: '+12 %', current: '2026', last: 'Last year' },
      },
      semantic: {
        catalogue: 'KPI catalogue',
        collection: 'KPI collection Revenue',
        definition: 'Definition',
        formula: 'Formula',
        dimensions: 'Dimensions',
        version: 'Version',
        guests: 'Guest data: not included',
        same: 'Three times the same number, one definition',
        consumers: ['Dashboard', 'Resi', 'Claude · MCP'],
        kpis: [
          { name: 'RevPAR', formula: 'net_revenue / rooms_available', dims: 'Channel · Room category · Arrival', version: 'v1.2', value: '119 €' },
          { name: 'ADR', formula: 'net_revenue / rooms_sold', dims: 'Channel · Origin · Arrival', version: 'v1.1', value: '142 €' },
          { name: 'Occupancy', formula: 'rooms_sold / rooms_available', dims: 'Room category · Arrival', version: 'v1.0', value: '84 %' },
        ],
        others: ['Ad spend', 'Requests'],
      },
      dimensions: {
        kpi: 'Pickup · 7 days',
        nights: 'nights',
        grouping: 'Grouping',
        groups: [
          { name: 'Channel', bars: [['Direct', 92], ['Booking', 58], ['Expedia', 34], ['Phone', 22]] },
          { name: 'Room category', bars: [['Double', 84], ['Superior', 62], ['Suite', 30], ['Single', 44]] },
          { name: 'Origin', bars: [['DE', 88], ['CH', 52], ['AT', 40], ['IT', 26]] },
        ],
        perspective: 'Perspective',
        perspectives: [
          { name: 'Booking date', field: 'booking.created_at', value: '38' },
          { name: 'Arrival', field: 'reservation.arrival', value: '52' },
        ],
        linked: 'Across collections',
        link: ['Campaign', 'Google Ads ↔ Mews', 'linked'],
        inWidgets: 'Selectable in every widget',
      },
      collections: {
        title: 'KPI collection',
        name: 'Hotel standard',
        version: 'v2.3',
        counts: '24 KPIs · 9 dimensions',
        items: ['Occupancy', 'ADR', 'RevPAR', 'Pickup', 'Cost per booking', 'Requests'],
        owner: 'Maintained by: head office',
        released: 'Released',
        readOnly: 'Read-only · updates arrive',
        groups: [
          { name: 'Hotel group', members: ['Alpenrose', 'Seeblick', 'Bergwald'] },
          { name: 'Clients', members: ['Hotel Post', 'Villa Laguna'] },
          { name: 'Community', members: ['Public · 140 spaces'] },
        ],
      },
      sync: {
        title: 'Sync: connect it yourself or send a secure link to a colleague or client, the history loads, then only what is new, duplicates removed and data cleansed, ready for dashboards, Resi and MCP',
        connect: 'Connect',
        noPassword: 'You never see a password',
        methods: [
          { who: 'You', role: 'connect it yourself', action: 'Sign in with Mews' },
          { who: 'Anna', role: 'Colleague, marketing', action: 'Link to Anna' },
          { who: 'Seeblick Resort', role: 'Client', action: 'Link to the client' },
        ],
        once: 'single use',
        expires: 'valid for 7 days',
        waiting: 'Waiting for approval',
        connected: 'Connected',
        approved: 'Approved',
        gate: 'Dedupe & cleanse',
        dupes: 'duplicates',
        cleaned: 'cleansed',
        datasets: ['Reservations', 'Campaigns & cost', 'Bookings'],
        rows: 'rows',
        history: 'History 13 months',
        then: 'then hourly',
        upToDate: 'Up to date',
        readyFor: 'Ready for',
      },
      verify: {
        title: 'Resi working on a dashboard: she answers a question with a checked source and puts the chart on the dashboard as a widget herself, then rebuilds the ADR widget by channel on request',
        dashboard: 'Q4 overview',
        period: 'Oct – Dec',
        turns: [
          { context: 'Q4 overview', q: 'How did ADR develop in October?', a: '−3.1 % to €138, mostly from more OTA bookings midweek.' },
          { context: 'ADR widget', q: 'Show ADR in the widget by channel instead.', a: 'Done: the ADR widget now shows direct, OTA and other.' },
        ],
        thinking: 'Resi is checking the KPI catalogue …',
        chart: 'ADR October, by week',
        source: 'ADR v1.1 from the KPI catalogue',
        verified: 'checked',
        placing: 'Resi is putting it on the dashboard …',
        placed: 'On the dashboard as a widget',
        slot: 'New widget',
        created: 'new from Resi',
        edited: 'edited by Resi',
        other: 'Other',
      },
    },
  },
} satisfies Record<Locale, unknown>

export const labelsFor = (locale?: Locale | null) => labels[locale === 'en' ? 'en' : 'de']
