import type { Locale } from '@/i18n/config'

/** Demo labels inside the illustrations. Numbers stay identical across languages. */
export const labels = {
  de: {
    occupancy: 'Auslastung',
    adr: 'ADR',
    revpar: 'RevPAR',
    bookings: 'Buchungen',
    direct: 'Direkt',
    ota: 'OTA',
    plan: 'Plan',
    lastYear: 'Vorjahr',
    thisYear: 'Dieses Jahr',
    sourcesOk: 'Alle 4 Datenquellen aktuell',
    healthy: 'Gesund',
    syncing: 'Aktualisiert',
    question: 'Warum ist der Pickup diese Woche höher?',
    answer: 'Vor allem mehr Direktbuchungen fürs Wochenende: +18 % gegenüber der Vorwoche.',
    you: 'Sie',
    agent: 'Indicate Agent',
    space: 'Space',
    owner: 'Owner',
    admin: 'Admin',
    reader: 'Leser',
    twoFactor: '2FA',
    pickup: 'Pickup diese Woche',
    otaShare: 'OTA-Anteil über Ziel',
    cpb: 'Kosten pro Buchung',
    week: 'Woche',
    march: 'März',
    vsLastYear: 'vs. Vorjahr',
    ask: 'Frage stellen …',
    q1: 'Wie war die Auslastung letzte Woche?',
    q2: 'Welche Kanäle bringen die meisten Direktbuchungen?',
    a1: 'Letzte Woche lag die Auslastung bei 84 %, 6 Punkte über der Vorwoche.',
    lastWeek: 'letzte Woche',
    months: ['Jan', 'Feb', 'Mär', 'Apr', 'Mai', 'Jun'],
  },
  en: {
    occupancy: 'Occupancy',
    adr: 'ADR',
    revpar: 'RevPAR',
    bookings: 'Bookings',
    direct: 'Direct',
    ota: 'OTA',
    plan: 'Plan',
    lastYear: 'Last year',
    thisYear: 'This year',
    sourcesOk: 'All 4 sources up to date',
    healthy: 'Healthy',
    syncing: 'Synced',
    question: 'Why is pickup higher this week?',
    answer: 'Mostly more direct bookings for the weekend: +18 % versus last week.',
    you: 'You',
    agent: 'Indicate agent',
    space: 'Space',
    owner: 'Owner',
    admin: 'Admin',
    reader: 'Reader',
    twoFactor: '2FA',
    pickup: 'Pickup this week',
    otaShare: 'OTA share above target',
    cpb: 'Cost per booking',
    week: 'Week',
    march: 'March',
    vsLastYear: 'vs. last year',
    ask: 'Ask a question …',
    q1: 'What was occupancy last week?',
    q2: 'Which channels bring the most direct bookings?',
    a1: 'Occupancy was 84 % last week, 6 points above the week before.',
    lastWeek: 'last week',
    months: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
  },
} satisfies Record<Locale, unknown>

export const labelsFor = (locale?: Locale | null) => labels[locale === 'en' ? 'en' : 'de']
