import type { Locale } from '@/i18n/config'

/** Demo labels inside the illustrations. Numbers stay identical across languages. */
export const labels = {
  de: {
    occupancy: 'Auslastung',
    adr: 'ADR',
    revpar: 'RevPAR',
    bookings: 'Buchungen',
    direct: 'Direkt',
    ota: 'OTA',
    plan: 'Plan',
    lastYear: 'Vorjahr',
    thisYear: 'Dieses Jahr',
    sourcesOk: 'Alle 4 Datenquellen aktuell',
    healthy: 'Gesund',
    syncing: 'Aktualisiert',
    question: 'Warum ist der Pickup diese Woche höher?',
    answer: 'Vor allem mehr Direktbuchungen fürs Wochenende: +18 % gegenüber der Vorwoche.',
    you: 'Sie',
    agent: 'Resi',
    space: 'Space',
    owner: 'Owner',
    admin: 'Admin',
    reader: 'Leser',
    twoFactor: '2FA',
    pickup: 'Pickup diese Woche',
    otaShare: 'OTA-Anteil über Ziel',
    cpb: 'Kosten pro Buchung',
    week: 'Woche',
    march: 'März',
    vsLastYear: 'vs. Vorjahr',
    ask: 'Frage stellen …',
    q1: 'Wie war die Auslastung letzte Woche?',
    q2: 'Welche Kanäle bringen die meisten Direktbuchungen?',
    a1: 'Letzte Woche lag die Auslastung bei 84 %, 6 Punkte über der Vorwoche.',
    lastWeek: 'letzte Woche',
    months: ['Jan', 'Feb', 'Mär', 'Apr', 'Mai', 'Jun'],
    scenes: {
      assistant: 'Assistent',
      builderPrompt: 'Baue ein Dashboard mit Auslastung, ADR und Kanalmix für Q4.',
      builderThinking: 'Kennzahlen werden ausgewählt …',
      builderDone: 'Dashboard gespeichert · Link kopiert',
      channelMix: 'Kanalmix',
      bookingsByWeek: 'Buchungen pro Woche',
      vsPlan: 'vs. Plan',
      schedule: 'Montag, 08:00',
      reportTitle: 'Wochenreport · KW 37',
      reportKind: 'PDF + Digest',
      delivered: 'Zugestellt',
      recipients: ['Geschäftsführung', 'Eigentümer', 'Revenue-Team'],
      groupTotal: 'Gruppe gesamt',
      campaignRoi: 'Kampagnen-ROI',
      adSpend: 'Werbekosten',
      revenue: 'Umsatz',
      roi: 'ROI',
      reportSent: 'Report gesendet',
      gap: 'Lücke: Oktober ohne Kampagne',
      clients: ['Hotel Alpenrose', 'Seeblick Resort', 'Bergwald Lodge'],
      properties: ['Alpenrose', 'Seeblick', 'Bergwald', 'Stadthof'],
      planVsActual: 'Plan vs. Ist',
      perProperty: 'je Haus',
      pickup: 'Pickup 7 Tage',
      scheduled: 'Geplant',
      created: 'Erstellt',
      sent: 'Gesendet',
      strategy: 'Strategie Q4',
      sharedWith: 'geteilt mit Kunde',
      comment: 'Oktober-Lücke schließen? Meta-Kampagne ab KW 40.',
      commentBy: 'Lena, Agentur',
      reply: 'Budget freigegeben.',
      replyBy: 'Kunde',
      automation: 'Monatsreport',
      automationText: '12 Kunden · automatisch am 1.',
      underHood: 'Unter der Haube',
      log: [
        ['mews', 'reservations', '1.284 Zeilen', '0,8 s'],
        ['google-ads', 'campaigns', '312 Zeilen', '0,4 s'],
        ['re-guest', 'requests', '96 Zeilen', '0,3 s'],
        ['meta', 'adsets', '48 Zeilen', '0,2 s'],
      ],
      chat: {
        title: 'Chat mit Ihren Daten',
        context: 'Kontext',
        question: 'Welche Zimmerkategorie verkauft sich im Oktober am schlechtesten?',
        answer: 'Die Juniorsuiten: 61 % Auslastung im Oktober, 14 Punkte unter dem Haus. Unter der Woche bleiben sie frei, am Wochenende sind sie fast voll.',
        kpi: 'Auslastung Juniorsuite · Oktober',
        source: 'Quelle: Mews · Reservierungen · KPI-Sammlung Revenue v1.2',
        sources: ['Mews PMS', 'Google Ads', 'Re:Guest'],
        followUps: ['Und im November?', 'Vergleich mit dem Vorjahr', 'Als Widget aufs Dashboard'],
        scope: 'Space: Hotel Alpenrose · Rolle: Admin',
        model: 'Modell: Claude Sonnet 5 · Sprache: Deutsch',
        aboutDashboard: 'Über dieses Dashboard chatten',
      },
      resi: {
        title: 'Resi bei der Arbeit: Quellen, Kennzahl-Definition und Rechte fließen in jede Antwort',
        role: 'Ihre KI-Agentin',
        thinking: 'Resi prüft die Kennzahlen …',
        catalogue: 'KPI-Katalog',
        permissions: 'Rechte wie in der App',
        scope: 'Space Alpenrose · Revenue-Team',
        source: 'Quelle',
        turns: [
          {
            q: 'Wie war die Auslastung letzte Woche?',
            a: '84 %, sechs Punkte über der Vorwoche. Der Zuwachs kam fast ganz aus Direktbuchungen.',
            kpi: 'Auslastung · KW 37',
            value: 84,
            unit: ' %',
            delta: '+6',
            up: true,
            lang: 'DE',
            def: 'Auslastung · v1.2',
          },
          {
            q: 'Hat die Sommerkampagne auf Meta den Plan erreicht?',
            a: 'Fast: 212 statt 240 Buchungen, dafür 168 € ADR über Plan. Die Lücke liegt in KW 29 bis 31.',
            kpi: 'Buchungen · Sommerkampagne',
            value: 212,
            unit: '',
            delta: '−28',
            up: false,
            lang: 'DE',
            def: 'Kampagnen-Buchungen · v2.0',
          },
          {
            q: 'Quale mercato porta l’ADR più alto?',
            a: 'Gli ospiti svizzeri: 189 € di ADR con 4,2 notti. Il 71 % prenota direttamente.',
            kpi: 'ADR · Svizzera',
            value: 189,
            unit: ' €',
            delta: '+31 %',
            up: true,
            lang: 'IT',
            def: 'ADR · v1.1',
          },
        ],
      },
      hub: {
        title: 'Resi im Zentrum: Datenquellen fließen in den Chat, jede Antwort wird zu Kennzahl oder Diagramm',
        role: 'Ihre KI-Agentin',
        ask: 'Fragen Sie Resi …',
        thinking: 'Resi prüft die Kennzahlen …',
        catalogue: 'KPI-Katalog',
        turns: [
          {
            q: 'Wie war die Auslastung letzte Woche?',
            a: '84 %, sechs Punkte über der Vorwoche. Der Zuwachs kam fast ganz aus Direktbuchungen.',
            source: 'Mews · Google Analytics',
            def: 'occupancy = rooms_sold / rooms_available',
          },
          {
            q: 'Hat die Meta-Kampagne den Plan erreicht?',
            a: 'Fast: 212 von 240 Buchungen. Die Lücke liegt in KW 29 bis 31.',
            source: 'Meta Ads · Mews',
            def: 'campaign_bookings = bookings where utm = meta',
          },
          {
            q: 'Wie läuft der Pickup für Oktober?',
            a: '12 % über Vorjahr, getragen von Google Ads. Ich schicke es Montag ans Revenue-Team.',
            source: 'Mews · Google Ads',
            def: 'pickup = Δ on_the_books per day',
          },
        ],
        kpi: { label: 'Auslastung · KW 37', delta: '+6' },
        bars: { title: 'Buchungen Meta-Kampagne', value: '212 / 240', actual: 'Ist', plan: 'Plan', from: 'KW 27', to: 'KW 34' },
        line: { title: 'Pickup Oktober', delta: '+12 %', current: '2026', last: 'Vorjahr' },
      },
      mcp: {
        title: 'Claude Desktop',
        clients: ['Claude', 'ChatGPT', 'Claude Code', 'Langdock', 'GitHub Copilot'],
        prompt: 'Wie lief die Sommerkampagne auf Meta gegen die Buchungen aus Mews?',
        tools: [
          ['list_kpis', 'kampagnen, buchungen'],
          ['get_kpi', 'meta_ad_spend · Jun–Aug'],
          ['get_kpi', 'total_bookings · Jun–Aug'],
        ],
        answer: '212 Buchungen bei 4.900 € Werbekosten, ADR 168 €. Die Lücke liegt in KW 29 bis 31: dort lief keine Anzeige.',
        server: 'Indicate MCP Server',
        endpoint: 'industry.indicate-data.io/mcp',
        catalogue: 'Kennzahlen-Katalog',
        permission: 'Rechte wie in der App',
        privacy: 'Gästedaten bleiben im Space',
        token: 'Agent-Token · Space Alpenrose',
        calls: 'Aufrufe',
      },
      studio: {
        file: 'revpar.v1.2.json',
        collection: 'KPI-Sammlung Revenue',
        preview: 'Vorschau (Dry Run)',
        dimensions: 'Dimensionen',
        dims: ['Kanal', 'Zimmerkategorie', 'Herkunft', 'Ankunftsdatum'],
        versions: 'Versionen',
        released: 'Freigegeben',
        usedIn: 'In 6 Dashboards und im Agenten',
        changelog: ['v1.0 · Umsatz / verfügbare Zimmer', 'v1.1 · Stornos ausgenommen', 'v1.2 · Frühstück getrennt'],
      },
      semantic: {
        catalogue: 'Kennzahlen-Katalog',
        collection: 'KPI-Sammlung Revenue',
        definition: 'Definition',
        formula: 'Formel',
        dimensions: 'Dimensionen',
        version: 'Version',
        guests: 'Gästedaten: nicht enthalten',
        same: 'Dreimal dieselbe Zahl, eine Definition',
        consumers: ['Dashboard', 'Resi', 'Claude · MCP'],
        kpis: [
          { name: 'RevPAR', formula: 'net_revenue / rooms_available', dims: 'Kanal · Zimmerkategorie · Ankunft', version: 'v1.2', value: '119 €' },
          { name: 'ADR', formula: 'net_revenue / rooms_sold', dims: 'Kanal · Herkunft · Ankunft', version: 'v1.1', value: '142 €' },
          { name: 'Auslastung', formula: 'rooms_sold / rooms_available', dims: 'Zimmerkategorie · Ankunft', version: 'v1.0', value: '84 %' },
        ],
        others: ['Werbekosten', 'Anfragen'],
      },
      dimensions: {
        kpi: 'Pickup · 7 Tage',
        nights: 'Nächte',
        grouping: 'Gruppierung',
        groups: [
          { name: 'Kanal', bars: [['Direkt', 92], ['Booking', 58], ['Expedia', 34], ['Telefon', 22]] },
          { name: 'Zimmerkategorie', bars: [['Doppel', 84], ['Superior', 62], ['Suite', 30], ['Einzel', 44]] },
          { name: 'Herkunft', bars: [['DE', 88], ['CH', 52], ['AT', 40], ['IT', 26]] },
        ],
        perspective: 'Perspektive',
        perspectives: [
          { name: 'Buchungsdatum', field: 'booking.created_at', value: '38' },
          { name: 'Ankunft', field: 'reservation.arrival', value: '52' },
        ],
        linked: 'Über Sammlungen hinweg',
        link: ['Kampagne', 'Google Ads ↔ Mews', 'verknüpft'],
        inWidgets: 'In jedem Widget wählbar',
      },
      collections: {
        title: 'KPI-Sammlung',
        name: 'Hotel-Standard',
        version: 'v2.3',
        counts: '24 Kennzahlen · 9 Dimensionen',
        items: ['Auslastung', 'ADR', 'RevPAR', 'Pickup', 'Kosten je Buchung', 'Anfragen'],
        owner: 'Gepflegt von: Zentrale',
        released: 'Freigegeben',
        readOnly: 'Lesend · Updates kommen an',
        groups: [
          { name: 'Hotelgruppe', members: ['Alpenrose', 'Seeblick', 'Bergwald'] },
          { name: 'Kunden', members: ['Hotel Post', 'Villa Laguna'] },
          { name: 'Community', members: ['Öffentlich · 140 Spaces'] },
        ],
      },
      templates: {
        title: 'Vorlagen',
        items: ['Mews · Revenue & Auslastung', 'Google Ads · Kampagnen', 'Re:Guest · Anfragen & Angebote'],
        by: ['Indicate', 'Indicate', 'Ihre Agentur'],
        apply: 'Anwenden auf',
        applied: 'Angewendet',
        remap: 'Kennzahlen zugeordnet',
        widgets: ['Auslastung', 'ADR', 'RevPAR', 'Umsatz je Kanal'],
        adWidgets: ['Werbekosten', 'Kosten je Buchung', 'ROAS', 'Klicks je Kampagne'],
        crmWidgets: ['Anfragen', 'Angebote', 'Abschlussquote', 'Antwortzeit'],
      },
      governance: {
        org: 'Organisation · Alpen Hotels',
        spaces: ['Hotel Alpenrose', 'Seeblick Resort', 'Bergwald Lodge'],
        members: 'Mitglieder',
        roles: ['Owner', 'Admin', 'User', 'Reader', 'Guest'],
        areas: ['Dashboards', 'Daten & KPIs', 'Team', 'Abrechnung'],
        policy: '2FA Pflicht',
        rolesLabel: 'Rollen',
        tokens: 'API-, Agent- und Service-Tokens',
        audit: 'Audit-Log',
        retention: '30 Tage',
        log: [
          ['09:12', 'Lena H.', 'Dashboard geteilt · Wochenreport'],
          ['09:40', 'System', 'Sync Mews · 1.284 Zeilen'],
          ['10:05', 'Jonas K.', 'Verbindungslink genutzt · Google Ads'],
          ['10:31', 'Anna B.', 'API-Token erstellt · Multi-Space'],
        ],
      },
      sync: {
        title: 'Verbindungen',
        rows: [
          ['Mews', 'Reservierungen, Raten', 'stündlich'],
          ['Google Ads', 'Kampagnen, Kosten', 'stündlich'],
          ['Re:Guest', 'Anfragen, Angebote', 'täglich'],
          ['Meta Ads', 'Anzeigengruppen', 'täglich'],
        ],
        busy: 'Aktualisiert …',
        ok: 'Aktuell',
        history: 'Historie ab dem ersten Tag',
        historyNote: '13 Monate · nachgeladen',
        historyStart: '−13 Monate',
        historyEnd: 'heute',
        invite: 'Verbindungslink',
        inviteText: 'Das Hotel gibt sein PMS selbst frei. Sie sehen nie ein Passwort.',
        inviteSteps: ['Link senden', 'Hotel bestätigt', 'Daten fließen'],
      },
      kpiStudio: 'KPI Studio',
      weeklyReport: 'Wochenreport',
    },
  },
  en: {
    occupancy: 'Occupancy',
    adr: 'ADR',
    revpar: 'RevPAR',
    bookings: 'Bookings',
    direct: 'Direct',
    ota: 'OTA',
    plan: 'Plan',
    lastYear: 'Last year',
    thisYear: 'This year',
    sourcesOk: 'All 4 sources up to date',
    healthy: 'Healthy',
    syncing: 'Synced',
    question: 'Why is pickup higher this week?',
    answer: 'Mostly more direct bookings for the weekend: +18 % versus last week.',
    you: 'You',
    agent: 'Resi',
    space: 'Space',
    owner: 'Owner',
    admin: 'Admin',
    reader: 'Reader',
    twoFactor: '2FA',
    pickup: 'Pickup this week',
    otaShare: 'OTA share above target',
    cpb: 'Cost per booking',
    week: 'Week',
    march: 'March',
    vsLastYear: 'vs. last year',
    ask: 'Ask a question …',
    q1: 'What was occupancy last week?',
    q2: 'Which channels bring the most direct bookings?',
    a1: 'Occupancy was 84 % last week, 6 points above the week before.',
    lastWeek: 'last week',
    months: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
    scenes: {
      assistant: 'Assistant',
      builderPrompt: 'Build a dashboard with occupancy, ADR and channel mix for Q4.',
      builderThinking: 'Choosing KPIs …',
      builderDone: 'Dashboard saved · link copied',
      channelMix: 'Channel mix',
      bookingsByWeek: 'Bookings per week',
      vsPlan: 'vs. plan',
      schedule: 'Monday, 08:00',
      reportTitle: 'Weekly report · week 37',
      reportKind: 'PDF + digest',
      delivered: 'Delivered',
      recipients: ['Management', 'Owners', 'Revenue team'],
      groupTotal: 'Group total',
      campaignRoi: 'Campaign ROI',
      adSpend: 'Ad spend',
      revenue: 'Revenue',
      roi: 'ROI',
      reportSent: 'Report sent',
      gap: 'Gap: no campaign in October',
      clients: ['Hotel Alpenrose', 'Seeblick Resort', 'Bergwald Lodge'],
      properties: ['Alpenrose', 'Seeblick', 'Bergwald', 'Stadthof'],
      planVsActual: 'Plan vs. actual',
      perProperty: 'per property',
      pickup: 'Pickup 7 days',
      scheduled: 'Scheduled',
      created: 'Created',
      sent: 'Sent',
      strategy: 'Strategy Q4',
      sharedWith: 'shared with client',
      comment: 'Close the October gap? Meta campaign from week 40.',
      commentBy: 'Lena, agency',
      reply: 'Budget approved.',
      replyBy: 'Client',
      automation: 'Monthly report',
      automationText: '12 clients · automatic on the 1st',
      underHood: 'Under the hood',
      log: [
        ['mews', 'reservations', '1,284 rows', '0.8 s'],
        ['google-ads', 'campaigns', '312 rows', '0.4 s'],
        ['re-guest', 'requests', '96 rows', '0.3 s'],
        ['meta', 'adsets', '48 rows', '0.2 s'],
      ],
      chat: {
        title: 'Chat with your data',
        context: 'Context',
        question: 'Which room category sells worst in October?',
        answer: 'The junior suites: 61 % occupancy in October, 14 points below the property. They stay empty on weekdays; at weekends they are almost full.',
        kpi: 'Junior suite occupancy · October',
        source: 'Source: Mews · reservations · KPI collection Revenue v1.2',
        sources: ['Mews PMS', 'Google Ads', 'Re:Guest'],
        followUps: ['And in November?', 'Compare with last year', 'Add as a dashboard widget'],
        scope: 'Space: Hotel Alpenrose · Role: Admin',
        model: 'Model: Claude Sonnet 5 · Language: English',
        aboutDashboard: 'Chat about this dashboard',
      },
      resi: {
        title: 'Resi at work: sources, KPI definitions and permissions flow into every answer',
        role: 'Your AI agent',
        thinking: 'Resi is checking the figures …',
        catalogue: 'KPI catalogue',
        permissions: 'Same permissions as in the app',
        scope: 'Space Alpenrose · revenue team',
        source: 'Source',
        turns: [
          {
            q: 'How was occupancy last week?',
            a: '84 %, six points above the week before. Almost all of the gain came from direct bookings.',
            kpi: 'Occupancy · week 37',
            value: 84,
            unit: ' %',
            delta: '+6',
            up: true,
            lang: 'EN',
            def: 'Occupancy · v1.2',
          },
          {
            q: 'Did the summer campaign on Meta hit plan?',
            a: 'Almost: 212 bookings against 240, but with an ADR of €168 above plan. The gap sits in weeks 29 to 31.',
            kpi: 'Bookings · summer campaign',
            value: 212,
            unit: '',
            delta: '−28',
            up: false,
            lang: 'EN',
            def: 'Campaign bookings · v2.0',
          },
          {
            q: 'Quale mercato porta l’ADR più alto?',
            a: 'Gli ospiti svizzeri: 189 € di ADR con 4,2 notti. Il 71 % prenota direttamente.',
            kpi: 'ADR · Svizzera',
            value: 189,
            unit: ' €',
            delta: '+31 %',
            up: true,
            lang: 'IT',
            def: 'ADR · v1.1',
          },
        ],
      },
      hub: {
        title: 'Resi at the centre: data sources flow into the chat, every answer becomes a KPI or a chart',
        role: 'Your AI agent',
        ask: 'Ask Resi …',
        thinking: 'Resi is checking the figures …',
        catalogue: 'KPI catalogue',
        turns: [
          {
            q: 'How was occupancy last week?',
            a: '84 %, six points above the week before. Almost all of the gain came from direct bookings.',
            source: 'Mews · Google Analytics',
            def: 'occupancy = rooms_sold / rooms_available',
          },
          {
            q: 'Did the Meta campaign hit plan?',
            a: 'Almost: 212 of 240 bookings. The gap sits in weeks 29 to 31.',
            source: 'Meta Ads · Mews',
            def: 'campaign_bookings = bookings where utm = meta',
          },
          {
            q: 'How is October pickup looking?',
            a: '12 % above last year, carried by Google Ads. I will send it to the revenue team on Monday.',
            source: 'Mews · Google Ads',
            def: 'pickup = Δ on_the_books per day',
          },
        ],
        kpi: { label: 'Occupancy · week 37', delta: '+6' },
        bars: { title: 'Meta campaign bookings', value: '212 / 240', actual: 'Actual', plan: 'Plan', from: 'Wk 27', to: 'Wk 34' },
        line: { title: 'October pickup', delta: '+12 %', current: '2026', last: 'Last year' },
      },
      mcp: {
        title: 'Claude Desktop',
        clients: ['Claude', 'ChatGPT', 'Claude Code', 'Langdock', 'GitHub Copilot'],
        prompt: 'How did the summer campaign on Meta do against the bookings in Mews?',
        tools: [
          ['list_kpis', 'campaigns, bookings'],
          ['get_kpi', 'meta_ad_spend · Jun–Aug'],
          ['get_kpi', 'total_bookings · Jun–Aug'],
        ],
        answer: '212 bookings on €4,900 ad spend, ADR €168. The gap sits in weeks 29 to 31, when no ad was running.',
        server: 'Indicate MCP server',
        endpoint: 'industry.indicate-data.io/mcp',
        catalogue: 'KPI catalogue',
        permission: 'Same permissions as in the app',
        privacy: 'Guest data stays in the space',
        token: 'Agent token · space Alpenrose',
        calls: 'calls',
      },
      studio: {
        file: 'revpar.v1.2.json',
        collection: 'KPI collection Revenue',
        preview: 'Preview (dry run)',
        dimensions: 'Dimensions',
        dims: ['Channel', 'Room category', 'Origin', 'Arrival date'],
        versions: 'Versions',
        released: 'Released',
        usedIn: 'In 6 dashboards and the agent',
        changelog: ['v1.0 · revenue / rooms available', 'v1.1 · cancellations excluded', 'v1.2 · breakfast separated'],
      },
      semantic: {
        catalogue: 'KPI catalogue',
        collection: 'KPI collection Revenue',
        definition: 'Definition',
        formula: 'Formula',
        dimensions: 'Dimensions',
        version: 'Version',
        guests: 'Guest data: not included',
        same: 'Three times the same number, one definition',
        consumers: ['Dashboard', 'Resi', 'Claude · MCP'],
        kpis: [
          { name: 'RevPAR', formula: 'net_revenue / rooms_available', dims: 'Channel · Room category · Arrival', version: 'v1.2', value: '119 €' },
          { name: 'ADR', formula: 'net_revenue / rooms_sold', dims: 'Channel · Origin · Arrival', version: 'v1.1', value: '142 €' },
          { name: 'Occupancy', formula: 'rooms_sold / rooms_available', dims: 'Room category · Arrival', version: 'v1.0', value: '84 %' },
        ],
        others: ['Ad spend', 'Requests'],
      },
      dimensions: {
        kpi: 'Pickup · 7 days',
        nights: 'nights',
        grouping: 'Grouping',
        groups: [
          { name: 'Channel', bars: [['Direct', 92], ['Booking', 58], ['Expedia', 34], ['Phone', 22]] },
          { name: 'Room category', bars: [['Double', 84], ['Superior', 62], ['Suite', 30], ['Single', 44]] },
          { name: 'Origin', bars: [['DE', 88], ['CH', 52], ['AT', 40], ['IT', 26]] },
        ],
        perspective: 'Perspective',
        perspectives: [
          { name: 'Booking date', field: 'booking.created_at', value: '38' },
          { name: 'Arrival', field: 'reservation.arrival', value: '52' },
        ],
        linked: 'Across collections',
        link: ['Campaign', 'Google Ads ↔ Mews', 'linked'],
        inWidgets: 'Selectable in every widget',
      },
      collections: {
        title: 'KPI collection',
        name: 'Hotel standard',
        version: 'v2.3',
        counts: '24 KPIs · 9 dimensions',
        items: ['Occupancy', 'ADR', 'RevPAR', 'Pickup', 'Cost per booking', 'Requests'],
        owner: 'Maintained by: head office',
        released: 'Released',
        readOnly: 'Read-only · updates arrive',
        groups: [
          { name: 'Hotel group', members: ['Alpenrose', 'Seeblick', 'Bergwald'] },
          { name: 'Clients', members: ['Hotel Post', 'Villa Laguna'] },
          { name: 'Community', members: ['Public · 140 spaces'] },
        ],
      },
      templates: {
        title: 'Templates',
        items: ['Mews · Revenue & occupancy', 'Google Ads · Campaigns', 'Re:Guest · Requests & offers'],
        by: ['Indicate', 'Indicate', 'Your agency'],
        apply: 'Apply to',
        applied: 'Applied',
        remap: 'KPIs remapped',
        widgets: ['Occupancy', 'ADR', 'RevPAR', 'Revenue by channel'],
        adWidgets: ['Ad spend', 'Cost per booking', 'ROAS', 'Clicks per campaign'],
        crmWidgets: ['Requests', 'Offers', 'Conversion', 'Response time'],
      },
      governance: {
        org: 'Organisation · Alpen Hotels',
        spaces: ['Hotel Alpenrose', 'Seeblick Resort', 'Bergwald Lodge'],
        members: 'Members',
        roles: ['Owner', 'Admin', 'User', 'Reader', 'Guest'],
        areas: ['Dashboards', 'Data & KPIs', 'Team', 'Billing'],
        policy: '2FA required',
        rolesLabel: 'roles',
        tokens: 'API, agent and service tokens',
        audit: 'Audit log',
        retention: '30 days',
        log: [
          ['09:12', 'Lena H.', 'Dashboard shared · weekly report'],
          ['09:40', 'System', 'Sync Mews · 1,284 rows'],
          ['10:05', 'Jonas K.', 'Connect link used · Google Ads'],
          ['10:31', 'Anna B.', 'API token created · multi-space'],
        ],
      },
      sync: {
        title: 'Connections',
        rows: [
          ['Mews', 'Reservations, rates', 'hourly'],
          ['Google Ads', 'Campaigns, cost', 'hourly'],
          ['Re:Guest', 'Requests, offers', 'daily'],
          ['Meta Ads', 'Ad sets', 'daily'],
        ],
        busy: 'Refreshing …',
        ok: 'Up to date',
        history: 'History from day one',
        historyNote: '13 months · backfilled',
        historyStart: '−13 months',
        historyEnd: 'today',
        invite: 'Connect link',
        inviteText: 'The hotel authorises its PMS itself. You never see a password.',
        inviteSteps: ['Send link', 'Hotel confirms', 'Data flows'],
      },
      kpiStudio: 'KPI Studio',
      weeklyReport: 'Weekly report',
    },
  },
} satisfies Record<Locale, unknown>

export const labelsFor = (locale?: Locale | null) => labels[locale === 'en' ? 'en' : 'de']
